//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignupFormWithLoginFormMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Table
    {
        public int Id { get; set; }

        [DisplayName("First Name")]
        public string firstName { get; set; }

        [DisplayName("Last Name")]
        public string lastName { get; set; }

        [DisplayName("Gender")]
        public string gender { get; set; }

        [DisplayName("Age")]
        public Nullable<int> age { get; set; }

        [DisplayName("Email")]
        public string email { get; set; }

        [DisplayName("User Name")]
        public string username { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string confirm_password { get; set; }
    }
}
