//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carreg
    {
        public int Id { get; set; }
        public string carno { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string available { get; set; }
    }
}
