//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo_crud_application.Models
{
    using System;
    using System.Collections.Generic;
    using Repo_crud_application.Repository;

    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Salary { get; set; }

        public static implicit operator Employee(RepositoryEmpoyee v)
        {
            throw new NotImplementedException();
        }
    }
}
